[tool.poetry]
name = "htu-ebeam-transport-quadrupole-optimization"
version = "0.1.0"
description = "Use elegant and GEECS-PythonAPI to optimize electro- and permanent quadrupole magnets in BELLA HTU's electron beam transport system."
authors = ["Reinier van Mourik <reinier.vanmourik@tausystems.com>"]
readme = "README.md"
packages = [{include = "htu_ebeam_transport_quadrupole_optimization"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.10"
pint = "0.22"

# rsopt needs to be installed separately, because it uses pykern for its setup, 
# which poetry can't make known to it. See README.md

